function c(a){throw a;}var g=void 0,i=null;function aa(){return function(a){return a}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var p,q=this;function ba(){}
function r(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function s(a){return a!==g}function ca(a){return r(a)=="array"}function da(a){var b=r(a);return b=="array"||b=="object"&&typeof a.length=="number"}function u(a){return typeof a=="string"}function ea(a){return r(a)=="function"}function fa(a){a=r(a);return a=="object"||a=="array"||a=="function"}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ia=0;
function ja(a,b,d){return a.call.apply(a.bind,arguments)}function ka(a,b,d){var e=b||q;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,f);return a.apply(e,b)}}else return function(){return a.apply(e,arguments)}}function la(a,b,d){la=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ja:ka;return la.apply(i,arguments)}var ma=Date.now||function(){return+new Date};
function na(a){var b={},d;for(d in b)var e=(""+b[d]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e);return a}function w(a,b){function d(){}d.prototype=b.prototype;a.j=b.prototype;a.prototype=new d};function oa(a){if(!pa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(qa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(ra,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(sa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(ta,"&quot;"));return a}var qa=/&/g,ra=/</g,sa=/>/g,ta=/\"/g,pa=/[&<>\"]/,ua={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},va={"'":"\\'"};
function wa(a){var n;a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],d=0;d<a.length;d++){var e=a.charAt(d),f=e.charCodeAt(0),h=b,j=d+1,k;if(!(k=ua[e])){if(!(f>31&&f<127))if(e in va)e=va[e];else if(e in ua)n=va[e]=ua[e],e=n;else{f=e;k=e.charCodeAt(0);if(k>31&&k<127)f=e;else{if(k<256){if(f="\\x",k<16||k>256)f+="0"}else f="\\u",k<4096&&(f+="0");f+=k.toString(16).toUpperCase()}e=va[e]=f}k=e}h[j]=k}b.push('"');return b.join("")}}
function xa(a,b){for(var d=0,e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(e.length,f.length),j=0;d==0&&j<h;j++){var k=e[j]||"",n=f[j]||"",o=RegExp("(\\d*)(\\D*)","g"),v=RegExp("(\\d*)(\\D*)","g");do{var t=o.exec(k)||["","",""],P=v.exec(n)||["","",""];if(t[0].length==0&&P[0].length==0)break;d=ya(t[1].length==0?0:parseInt(t[1],10),P[1].length==0?0:parseInt(P[1],10))||ya(t[2].length==0,P[2].length==0)||ya(t[2],P[2])}while(d==
0)}return d}function ya(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}function za(a){for(var b=0,d=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;return b};var Aa,Ba,Ca,Da,Ea,Fa,Ga,Ha=(Ga="ScriptEngine"in q&&q.ScriptEngine()=="JScript")?q.ScriptEngineMajorVersion()+"."+q.ScriptEngineMinorVersion()+"."+q.ScriptEngineBuildVersion():"0";function Ia(a,b){this.v=Ga?[]:"";a!=i&&this.append.apply(this,arguments)}Ia.prototype.set=function(a){this.clear();this.append(a)};Ga?(Ia.prototype.Oa=0,Ia.prototype.append=function(a,b,d){b==i?this.v[this.Oa++]=a:(this.v.push.apply(this.v,arguments),this.Oa=this.v.length);return this}):Ia.prototype.append=function(a,b,d){this.v+=a;if(b!=i)for(var e=1;e<arguments.length;e++)this.v+=arguments[e];return this};Ia.prototype.clear=function(){Ga?this.Oa=this.v.length=0:this.v=""};
Ia.prototype.toString=function(){if(Ga){var a=this.v.join("");this.clear();a&&this.append(a);return a}else return this.v};var Ja;function Ka(){}Ka.prototype.bb=!1;Ka.prototype.o=function(){if(!this.bb)this.bb=!0,this.h()};Ka.prototype.h=function(){};var La=Array.prototype,Ma=La.indexOf?function(a,b,d){return La.indexOf.call(a,b,d)}:function(a,b,d){d=d==i?0:d<0?Math.max(0,a.length+d):d;if(u(a))return!u(b)||b.length!=1?-1:a.indexOf(b,d);for(;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1},Na=La.forEach?function(a,b,d){La.forEach.call(a,b,d)}:function(a,b,d){for(var e=a.length,f=u(a)?a.split(""):a,h=0;h<e;h++)h in f&&b.call(d,f[h],h,a)};function Oa(a){return La.concat.apply(La,arguments)}
function Pa(a){if(ca(a))return Oa(a);else{for(var b=[],d=0,e=a.length;d<e;d++)b[d]=a[d];return b}}function Qa(a,b,d){return arguments.length<=2?La.slice.call(a,b):La.slice.call(a,b,d)};function Ra(){return q.navigator?q.navigator.userAgent:i}function Sa(){return q.navigator}Ea=Da=Ca=Ba=Aa=!1;var Ta;if(Ta=Ra()){var Ua=Sa();Aa=Ta.indexOf("Opera")==0;Ba=!Aa&&Ta.indexOf("MSIE")!=-1;Da=(Ca=!Aa&&Ta.indexOf("WebKit")!=-1)&&Ta.indexOf("Mobile")!=-1;Ea=!Aa&&!Ca&&Ua.product=="Gecko"}var Va=Aa,x=Ba,Wa=Ea,y=Ca,Xa=Da,Ya=Sa();Fa=(Ya&&Ya.platform||"").indexOf("Mac")!=-1;var Za=!!Sa()&&(Sa().appVersion||"").indexOf("X11")!=-1,$a;
a:{var ab="",bb;if(Va&&q.opera)var cb=q.opera.version,ab=typeof cb=="function"?cb():cb;else if(Wa?bb=/rv\:([^\);]+)(\)|;)/:x?bb=/MSIE\s+([^\);]+)(\)|;)/:y&&(bb=/WebKit\/(\S+)/),bb)var db=bb.exec(Ra()),ab=db?db[1]:"";if(x){var eb,fb=q.document;eb=fb?fb.documentMode:g;if(eb>parseFloat(ab)){$a=String(eb);break a}}$a=ab}var gb={};function z(a){return gb[a]||(gb[a]=xa($a,a)>=0)};var hb=!x||z("9"),ib=x&&!z("8");function jb(a,b){this.type=a;this.currentTarget=this.target=b}w(jb,Ka);p=jb.prototype;p.h=function(){delete this.type;delete this.target;delete this.currentTarget};p.T=!1;p.qa=!0;p.stopPropagation=function(){this.T=!0};p.preventDefault=function(){this.qa=!1};function kb(a){a.preventDefault()};var lb=new Function("a","return a");function mb(a,b){a&&this.R(a,b)}w(mb,jb);var nb=[1,4,2];p=mb.prototype;p.target=i;p.relatedTarget=i;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=!1;p.altKey=!1;p.shiftKey=!1;p.metaKey=!1;p.Qb=!1;p.q=i;
p.R=function(a,b){var d=this.type=a.type;jb.call(this,d);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(Wa)try{lb(e.nodeName)}catch(f){e=i}}else if(d=="mouseover")e=a.fromElement;else if(d=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(d=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Qb=Fa?a.metaKey:a.ctrlKey;this.state=a.state;this.q=a;delete this.qa;delete this.T};p.stopPropagation=function(){mb.j.stopPropagation.call(this);this.q.stopPropagation?this.q.stopPropagation():this.q.cancelBubble=!0};
p.preventDefault=function(){mb.j.preventDefault.call(this);var a=this.q;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,ib)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};p.h=function(){mb.j.h.call(this);this.relatedTarget=this.currentTarget=this.target=this.q=i};function ob(){}var pb=0;p=ob.prototype;p.key=0;p.fa=!1;p.Ya=!1;p.R=function(a,b,d,e,f,h){ea(a)?this.kb=!0:a&&a.handleEvent&&ea(a.handleEvent)?this.kb=!1:c(Error("Invalid listener argument"));this.da=a;this.qb=b;this.src=d;this.type=e;this.capture=!!f;this.Ea=h;this.Ya=!1;this.key=++pb;this.fa=!1};p.handleEvent=function(a){return this.kb?this.da.call(this.Ea||this.src,a):this.da.handleEvent.call(this.da,a)};function A(a,b){this.lb=b;this.P=[];a>this.lb&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<a;d++)this.P.push(this.F?this.F():{})}w(A,Ka);A.prototype.F=i;A.prototype.ab=i;A.prototype.getObject=function(){return this.P.length?this.P.pop():this.F?this.F():{}};function qb(a,b){a.P.length<a.lb?a.P.push(b):rb(a,b)}function rb(a,b){if(a.ab)a.ab(b);else if(fa(b))if(ea(b.o))b.o();else for(var d in b)delete b[d]}
A.prototype.h=function(){A.j.h.call(this);for(var a=this.P;a.length;)rb(this,a.pop());delete this.P};var sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb;
(function(){function a(){return{l:0,u:0}}function b(){return[]}function d(){function a(b){return j.call(a.src,a.key,b)}return a}function e(){return new ob}function f(){return new mb}var h=Ga&&!(xa(Ha,"5.7")>=0),j;xb=function(a){j=a};if(h){sb=function(){return k.getObject()};tb=function(a){qb(k,a)};ub=function(){return n.getObject()};vb=function(a){qb(n,a)};wb=function(){return o.getObject()};yb=function(){qb(o,d())};zb=function(){return v.getObject()};Ab=function(a){qb(v,a)};Bb=function(){return t.getObject()};
Cb=function(a){qb(t,a)};var k=new A(0,600);k.F=a;var n=new A(0,600);n.F=b;var o=new A(0,600);o.F=d;var v=new A(0,600);v.F=e;var t=new A(0,600);t.F=f}else sb=a,tb=ba,ub=b,vb=ba,wb=d,yb=ba,zb=e,Ab=ba,Bb=f,Cb=ba})();function Db(a,b,d){for(var e in a)b.call(d,a[e],e,a)}function Eb(a){var b=[],d=0,e;for(e in a)b[d++]=a[e];return b}function Fb(a){var b=[],d=0,e;for(e in a)b[d++]=e;return b}function Gb(a){var b={},d;for(d in a)b[d]=a[d];return b}var Hb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function Ib(a,b){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)a[d]=e[d];for(var h=0;h<Hb.length;h++)d=Hb[h],Object.prototype.hasOwnProperty.call(e,d)&&(a[d]=e[d])}};var Jb={},B={},Kb={},Lb={};
function C(a,b,d,e,f){if(b)if(ca(b)){for(var h=0;h<b.length;h++)C(a,b[h],d,e,f);return i}else{var e=!!e,j=B;b in j||(j[b]=sb());j=j[b];e in j||(j[e]=sb(),j.l++);var j=j[e],k=ga(a),n;j.u++;if(j[k]){n=j[k];for(h=0;h<n.length;h++)if(j=n[h],j.da==d&&j.Ea==f){if(j.fa)break;return n[h].key}}else n=j[k]=ub(),j.l++;h=wb();h.src=a;j=zb();j.R(d,h,a,b,e,f);d=j.key;h.key=d;n.push(j);Jb[d]=j;Kb[k]||(Kb[k]=ub());Kb[k].push(j);a.addEventListener?(a==q||!a.$a)&&a.addEventListener(b,h,e):a.attachEvent(b in Lb?Lb[b]:
Lb[b]="on"+b,h);return d}else c(Error("Invalid event type"))}function Mb(a,b,d,e,f){if(ca(b))for(var h=0;h<b.length;h++)Mb(a,b[h],d,e,f);else if(e=!!e,a=Nb(a,b,e))for(h=0;h<a.length;h++)if(a[h].da==d&&a[h].capture==e&&a[h].Ea==f){D(a[h].key);break}}
function D(a){if(Jb[a]){var b=Jb[a];if(!b.fa){var d=b.src,e=b.type,f=b.qb,h=b.capture;d.removeEventListener?(d==q||!d.$a)&&d.removeEventListener(e,f,h):d.detachEvent&&d.detachEvent(e in Lb?Lb[e]:Lb[e]="on"+e,f);d=ga(d);f=B[e][h][d];if(Kb[d]){var j=Kb[d],k=Ma(j,b);k>=0&&La.splice.call(j,k,1);j.length==0&&delete Kb[d]}b.fa=!0;f.mb=!0;Ob(e,h,d,f);delete Jb[a]}}}
function Ob(a,b,d,e){if(!e.Ia&&e.mb){for(var f=0,h=0;f<e.length;f++)if(e[f].fa){var j=e[f].qb;j.src=i;yb(j);Ab(e[f])}else f!=h&&(e[h]=e[f]),h++;e.length=h;e.mb=!1;h==0&&(vb(e),delete B[a][b][d],B[a][b].l--,B[a][b].l==0&&(tb(B[a][b]),delete B[a][b],B[a].l--),B[a].l==0&&(tb(B[a]),delete B[a]))}}
function Pb(a){var b,d=0,e=b==i;b=!!b;if(a==i)Db(Kb,function(a){for(var f=a.length-1;f>=0;f--){var h=a[f];if(e||b==h.capture)D(h.key),d++}});else if(a=ga(a),Kb[a])for(var a=Kb[a],f=a.length-1;f>=0;f--){var h=a[f];if(e||b==h.capture)D(h.key),d++}}function Nb(a,b,d){var e=B;return b in e&&(e=e[b],d in e&&(e=e[d],a=ga(a),e[a]))?e[a]:i}
function Qb(a,b,d,e,f){var h=1,b=ga(b);if(a[b]){a.u--;a=a[b];a.Ia?a.Ia++:a.Ia=1;try{for(var j=a.length,k=0;k<j;k++){var n=a[k];n&&!n.fa&&(h&=Rb(n,f)!==!1)}}finally{a.Ia--,Ob(d,e,b,a)}}return Boolean(h)}function Rb(a,b){var d=a.handleEvent(b);a.Ya&&D(a.key);return d}
xb(function(a,b){if(!Jb[a])return!0;var d=Jb[a],e=d.type,f=B;if(!(e in f))return!0;var f=f[e],h,j;Ja===g&&(Ja=x&&!q.addEventListener);if(Ja){var k;if(!(k=b))a:{k="window.event".split(".");for(var n=q;h=k.shift();)if(n[h]!=i)n=n[h];else{k=i;break a}k=n}h=k;k=!0 in f;n=!1 in f;if(k){if(h.keyCode<0||h.returnValue!=g)return!0;a:{var o=!1;if(h.keyCode==0)try{h.keyCode=-1;break a}catch(v){o=!0}if(o||h.returnValue==g)h.returnValue=!0}}o=Bb();o.R(h,this);h=!0;try{if(k){for(var t=ub(),P=o.currentTarget;P;P=
P.parentNode)t.push(P);j=f[!0];j.u=j.l;for(var Z=t.length-1;!o.T&&Z>=0&&j.u;Z--)o.currentTarget=t[Z],h&=Qb(j,t[Z],e,!0,o);if(n){j=f[!1];j.u=j.l;for(Z=0;!o.T&&Z<t.length&&j.u;Z++)o.currentTarget=t[Z],h&=Qb(j,t[Z],e,!1,o)}}else h=Rb(d,o)}finally{if(t)t.length=0,vb(t);o.o();Cb(o)}return h}e=new mb(b,this);try{h=Rb(d,e)}finally{e.o()}return h});function Sb(a){this.gb=a}w(Sb,Ka);var Tb=new A(0,100),Ub=[];function E(a,b,d,e,f){ca(d)||(Ub[0]=d,d=Ub);for(var h=0;h<d.length;h++){var j=a,k=C(b,d[h],e||a,f||!1,a.gb||a);j.d?j.d[k]=!0:j.N?(j.d=Tb.getObject(),j.d[j.N]=!0,j.N=i,j.d[k]=!0):j.N=k}return a}
function Vb(a,b,d,e,f,h){if(a.N||a.d)if(ca(d))for(var j=0;j<d.length;j++)Vb(a,b,d[j],e,f,h);else{a:{e=e||a;h=h||a.gb||a;f=!!f;if(b=Nb(b,d,f))for(d=0;d<b.length;d++)if(b[d].da==e&&b[d].capture==f&&b[d].Ea==h){b=b[d];break a}b=i}if(b)if(b=b.key,D(b),a.d)d=a.d,b in d&&delete d[b];else if(a.N==b)a.N=i}return a}function Wb(a){if(a.d){for(var b in a.d)D(b),delete a.d[b];qb(Tb,a.d);a.d=i}else a.N&&D(a.N)}Sb.prototype.h=function(){Sb.j.h.call(this);Wb(this)};Sb.prototype.handleEvent=function(){c(Error("EventHandler.handleEvent not implemented"))};function Xb(){}w(Xb,Ka);p=Xb.prototype;p.$a=!0;p.La=i;p.Va=function(a){this.La=a};p.addEventListener=function(a,b,d,e){C(this,a,b,d,e)};p.removeEventListener=function(a,b,d,e){Mb(this,a,b,d,e)};
p.dispatchEvent=function(a){var b=a.type||a,d=B;if(b in d){if(u(a))a=new jb(a,this);else if(a instanceof jb)a.target=a.target||this;else{var e=a,a=new jb(b,this);Ib(a,e)}var e=1,f,d=d[b],b=!0 in d,h;if(b){f=[];for(h=this;h;h=h.La)f.push(h);h=d[!0];h.u=h.l;for(var j=f.length-1;!a.T&&j>=0&&h.u;j--)a.currentTarget=f[j],e&=Qb(h,f[j],a.type,!0,a)&&a.qa!=!1}if(!1 in d)if(h=d[!1],h.u=h.l,b)for(j=0;!a.T&&j<f.length&&h.u;j++)a.currentTarget=f[j],e&=Qb(h,f[j],a.type,!1,a)&&a.qa!=!1;else for(f=this;!a.T&&f&&
h.u;f=f.La)a.currentTarget=f,e&=Qb(h,f,a.type,!1,a)&&a.qa!=!1;a=Boolean(e)}else a=!0;return a};p.h=function(){Xb.j.h.call(this);Pb(this);this.La=i};var Yb=q.window;var Zb,$b=!x||z("9");!Wa&&!x||x&&z("9")||Wa&&z("1.9.1");x&&z("9");function ac(a,b){var d;d=(d=a.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e=Qa(arguments,1),f;f=d;for(var h=0,j=0;j<e.length;j++)Ma(f,e[j])>=0||(f.push(e[j]),h++);f=h==e.length;a.className=d.join(" ");return f};function bc(a,b){this.x=s(a)?a:0;this.y=s(b)?b:0}bc.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function cc(a,b){this.width=a;this.height=b}cc.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};cc.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};cc.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};cc.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function dc(a){return a?new ec(fc(a)):Zb||(Zb=new ec)}function gc(a){return u(a)?document.getElementById(a):a}function hc(a,b){Db(b,function(b,e){e=="style"?a.style.cssText=b:e=="class"?a.className=b:e=="for"?a.htmlFor=b:e in ic?a.setAttribute(ic[e],b):a[e]=b})}var ic={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function jc(a){var b=a.document;if(y&&!z("500")&&!Xa){typeof a.innerHeight=="undefined"&&(a=window);var b=a.innerHeight,d=a.document.documentElement.scrollHeight;a==a.top&&d<b&&(b-=15);return new cc(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"?b.documentElement:b.body;return new cc(a.clientWidth,a.clientHeight)}function kc(a,b,d){return lc(document,arguments)}
function lc(a,b){var d=b[0],e=b[1];if(!$b&&e&&(e.name||e.type)){d=["<",d];e.name&&d.push(' name="',oa(e.name),'"');if(e.type){d.push(' type="',oa(e.type),'"');var f={};Ib(f,e);e=f;delete e.type}d.push(">");d=d.join("")}d=a.createElement(d);if(e)u(e)?d.className=e:ca(e)?ac.apply(i,[d].concat(e)):hc(d,e);b.length>2&&mc(a,d,b,2);return d}
function mc(a,b,d,e){function f(d){d&&b.appendChild(u(d)?a.createTextNode(d):d)}for(;e<d.length;e++){var h=d[e];da(h)&&!(fa(h)&&h.nodeType>0)?Na(nc(h)?Pa(h):h,f):f(h)}}function oc(a){return document.createTextNode(a)}function pc(a,b){a.appendChild(b)}function qc(a){a&&a.parentNode&&a.parentNode.removeChild(a)}function rc(a,b){var d=b.parentNode;d&&d.replaceChild(a,b)}function fc(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function sc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var d;d=a.firstChild;)a.removeChild(d);a.appendChild(fc(a).createTextNode(b))}}function nc(a){if(a&&typeof a.length=="number")if(fa(a))return typeof a.item=="function"||typeof a.item=="string";else if(ea(a))return typeof a.item=="function";return!1}function ec(a){this.p=a||q.document||document}p=ec.prototype;
p.r=dc;function tc(a){return a.p}p.e=function(a){return u(a)?this.p.getElementById(a):a};p.m=function(a,b,d){return lc(this.p,arguments)};p.createElement=function(a){return this.p.createElement(a)};p.createTextNode=function(a){return this.p.createTextNode(a)};function uc(a){var b=a.p,a=!y&&b.compatMode=="CSS1Compat"?b.documentElement:b.body,b=b.parentWindow||b.defaultView;return new bc(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}p.appendChild=pc;
p.append=function(a,b){mc(fc(a),a,arguments,1)};function vc(a){a.setAttribute("role","dialog");a.Yb="dialog"};function wc(a){this.c=a;a=x?"focusout":"blur";this.Jb=C(this.c,x?"focusin":"focus",this,!x);this.Kb=C(this.c,a,this,!x)}w(wc,Xb);wc.prototype.handleEvent=function(a){var b=new mb(a.q);b.type=a.type=="focusin"||a.type=="focus"?"focusin":"focusout";try{this.dispatchEvent(b)}finally{b.o()}};wc.prototype.h=function(){wc.j.h.call(this);D(this.Jb);D(this.Kb);delete this.c};function xc(a,b,d,e,f){if(!x&&(!y||!z("525")))return!0;if(Fa&&f)return yc(a);if(f&&!e)return!1;if(!d&&(b==17||b==18))return!1;if(x&&e&&b==a)return!1;switch(a){case 13:return!0;case 27:return!y}return yc(a)}
function yc(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if(y&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}};function zc(a,b,d,e){this.left=a;this.top=b;this.width=d;this.height=e}zc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};function Ac(a,b,d){this.target=a;this.handle=b||a;this.Ta=d||new zc(NaN,NaN,NaN,NaN);this.p=fc(a);this.A=new Sb(this);C(this.handle,["touchstart","mousedown"],this.rb,!1,this)}w(Ac,Xb);var Bc=x||Wa&&z("1.9.3");p=Ac.prototype;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.sb=0;p.tb=0;p.la=0;p.ma=0;p.eb=!0;p.L=!1;p.ib=0;p.Mb=0;p.Hb=!1;p.aa=l("A");p.h=function(){Ac.j.h.call(this);Mb(this.handle,["touchstart","mousedown"],this.rb,!1,this);this.A.o();delete this.target;delete this.handle;delete this.A};
p.rb=function(a){var b=a.type=="mousedown";if(this.eb&&!this.L&&(!b||(hb?a.q.button==0:a.type=="click"||a.q.button&nb[0])&&(!y||!Fa||!a.ctrlKey))){Cc(a);if(this.ib==0)if(Dc(this,a),this.L)a.preventDefault();else return;else a.preventDefault();var b=this.p,d=b.documentElement,e=!Bc;E(this.A,b,["touchmove","mousemove"],this.Gb,e);E(this.A,b,["touchend","mouseup"],this.Aa,e);Bc?(d.setCapture(!1),E(this.A,d,"losecapture",this.Aa)):E(this.A,b?b.parentWindow||b.defaultView:window,"blur",this.Aa);x&&this.Hb&&
E(this.A,b,"dragstart",kb);this.Sb&&E(this.A,this.Sb,"scroll",this.Ob,e);this.clientX=this.sb=a.clientX;this.clientY=this.tb=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.la=this.target.offsetLeft;this.ma=this.target.offsetTop;this.pa=uc(dc(this.p));this.Mb=ma()}};function Dc(a,b){if(a.dispatchEvent(new Ec("start",a,b.clientX,b.clientY,b))!==!1)a.L=!0}
p.Aa=function(a,b){Wb(this.A);Bc&&this.p.releaseCapture();if(this.L)Cc(a),this.L=!1,this.dispatchEvent(new Ec("end",this,a.clientX,a.clientY,a,Fc(this,this.la),Gc(this,this.ma),b||a.type=="touchcancel"));(a.type=="touchend"||a.type=="touchcancel")&&a.preventDefault()};function Cc(a){var b=a.type;b=="touchstart"||b=="touchmove"?a.R(a.q.targetTouches[0],a.currentTarget):(b=="touchend"||b=="touchcancel")&&a.R(a.q.changedTouches[0],a.currentTarget)}
p.Gb=function(a){if(this.eb){Cc(a);var b=a.clientX-this.clientX,d=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.L){var e=this.sb-this.clientX,f=this.tb-this.clientY;if(e*e+f*f>this.ib&&(Dc(this,a),!this.L)){this.Aa(a);return}}d=Hc(this,b,d);b=d.x;d=d.y;this.L&&this.dispatchEvent(new Ec("beforedrag",this,a.clientX,a.clientY,a,b,d))!==!1&&(Ic(this,a,b,d),a.preventDefault())}};
function Hc(a,b,d){var e=uc(dc(a.p));b+=e.x-a.pa.x;d+=e.y-a.pa.y;a.pa=e;a.la+=b;a.ma+=d;return new bc(Fc(a,a.la),Gc(a,a.ma))}p.Ob=function(a){var b=Hc(this,0,0);a.clientX=this.pa.x-this.clientX;a.clientY=this.pa.y-this.clientY;Ic(this,a,b.x,b.y)};function Ic(a,b,d,e){a.target.style.left=d+"px";a.target.style.top=e+"px";a.dispatchEvent(new Ec("drag",a,b.clientX,b.clientY,b,d,e))}
function Fc(a,b){var d=a.Ta,e=!isNaN(d.left)?d.left:i,d=!isNaN(d.width)?d.width:0;return Math.min(e!=i?e+d:Infinity,Math.max(e!=i?e:-Infinity,b))}function Gc(a,b){var d=a.Ta,e=!isNaN(d.top)?d.top:i,d=!isNaN(d.height)?d.height:0;return Math.min(e!=i?e+d:Infinity,Math.max(e!=i?e:-Infinity,b))}function Ec(a,b,d,e,f,h,j,k){jb.call(this,a);this.clientX=d;this.clientY=e;this.Vb=f;this.left=s(h)?h:b.la;this.top=s(j)?j:b.ma;this.Xb=b;this.Wb=!!k}w(Ec,jb);function Jc(a){if(typeof a.Da=="function")return a.Da();if(u(a))return a.split("");if(da(a)){for(var b=[],d=a.length,e=0;e<d;e++)b.push(a[e]);return b}return Eb(a)}function Kc(a,b,d){if(typeof a.forEach=="function")a.forEach(b,d);else if(da(a)||u(a))Na(a,b,d);else{var e;if(typeof a.Ra=="function")e=a.Ra();else if(typeof a.Da!="function")if(da(a)||u(a)){e=[];for(var f=a.length,h=0;h<f;h++)e.push(h)}else e=Fb(a);else e=g;for(var f=Jc(a),h=f.length,j=0;j<h;j++)b.call(d,f[j],e&&e[j],a)}};function Lc(a,b){this.S={};this.d=[];var d=arguments.length;if(d>1){d%2&&c(Error("Uneven number of arguments"));for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else if(a){a instanceof Lc?(d=a.Ra(),e=a.Da()):(d=Fb(a),e=Eb(a));for(var f=0;f<d.length;f++)this.set(d[f],e[f])}}p=Lc.prototype;p.l=0;p.xb=0;p.Da=function(){Mc(this);for(var a=[],b=0;b<this.d.length;b++)a.push(this.S[this.d[b]]);return a};p.Ra=function(){Mc(this);return this.d.concat()};
p.clear=function(){this.S={};this.xb=this.l=this.d.length=0};function Mc(a){if(a.l!=a.d.length){for(var b=0,d=0;b<a.d.length;){var e=a.d[b];Object.prototype.hasOwnProperty.call(a.S,e)&&(a.d[d++]=e);b++}a.d.length=d}if(a.l!=a.d.length){for(var f={},d=b=0;b<a.d.length;)e=a.d[b],Object.prototype.hasOwnProperty.call(f,e)||(a.d[d++]=e,f[e]=1),b++;a.d.length=d}}p.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.S,a)?this.S[a]:b};
p.set=function(a,b){Object.prototype.hasOwnProperty.call(this.S,a)||(this.l++,this.d.push(a),this.xb++);this.S[a]=b};function Nc(a,b){var d=fc(a);return d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,i))?d[b]||d.getPropertyValue(b):""}function Oc(a,b,d){b instanceof cc?(d=b.height,b=b.width):d==g&&c(Error("missing height argument"));a.style.width=Pc(b,!0);a.style.height=Pc(d,!0)}function Pc(a,b){typeof a=="number"&&(a=(b?Math.round(a):a)+"px");return a}
function Qc(a){if((Nc(a,"display")||(a.currentStyle?a.currentStyle.display:i)||a.style.display)!="none")return new cc(a.offsetWidth,a.offsetHeight);var b=a.style,d=b.display,e=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";var h=a.offsetWidth,a=a.offsetHeight;b.display=d;b.position=f;b.visibility=e;return new cc(h,a)}
function Rc(a,b){var d=a.style;if("opacity"in d)d.opacity=b;else if("MozOpacity"in d)d.MozOpacity=b;else if("filter"in d)d.filter=b===""?"":"alpha(opacity="+b*100+")"}function F(a,b){a.style.display=b?"":"none"};function Sc(){}(function(a){a.fb=function(){return a.Ib||(a.Ib=new a)}})(Sc);Sc.prototype.nb=0;Sc.fb();function Tc(a){this.za=a||dc();this.Rb=Uc}w(Tc,Xb);Tc.prototype.jb=Sc.fb();var Uc=i;p=Tc.prototype;p.Fa=i;p.G=!1;p.c=i;p.Rb=i;p.Lb=i;p.ea=i;p.ta=i;p.ia=i;p.Ub=!1;p.e=l("c");p.aa=function(){return this.ba||(this.ba=new Sb(this))};p.Va=function(a){this.ea&&this.ea!=a&&c(Error("Method not supported"));Tc.j.Va.call(this,a)};p.r=l("za");p.m=function(){this.c=this.za.createElement("div")};
p.ga=function(a){this.G&&c(Error("Component already rendered"));this.c||this.m();a?a.insertBefore(this.c,i):this.za.p.body.appendChild(this.c);(!this.ea||this.ea.G)&&this.Ba()};p.Ba=function(){this.G=!0;Vc(this,function(a){!a.G&&a.e()&&a.Ba()})};p.na=function(){Vc(this,function(a){a.G&&a.na()});this.ba&&Wb(this.ba);this.G=!1};
p.h=function(){Tc.j.h.call(this);this.G&&this.na();this.ba&&(this.ba.o(),delete this.ba);Vc(this,function(a){a.o()});!this.Ub&&this.c&&qc(this.c);this.ea=this.Lb=this.c=this.ia=this.ta=i};function Vc(a,b){a.ta&&Na(a.ta,b,g)}
p.removeChild=function(a,b){if(a){var d=u(a)?a:a.Fa||(a.Fa=":"+(a.jb.nb++).toString(36)),a=this.ia&&d?(d in this.ia?this.ia[d]:g)||i:i;if(d&&a){var e=this.ia;d in e&&delete e[d];d=this.ta;e=Ma(d,a);e>=0&&La.splice.call(d,e,1);b&&(a.na(),a.c&&qc(a.c));d=a;d==i&&c(Error("Unable to set parent component"));d.ea=i;Tc.j.Va.call(d,i)}}a||c(Error("Child is not in parent component"));return a};function Wc(a,b,d){Tc.call(this,d);this.t=a||"modal-dialog";this.Wa=!!b;this.s=G(G(new Xc,Yc,!0),Zc,!1,!0)}w(Wc,Tc);p=Wc.prototype;p.Ca=i;p.Cb=!0;p.hb=!0;p.Wa=!1;p.Ja=!0;p.cb=!0;p.yb=0.5;p.wb="";p.Qa="";p.s=i;p.$=i;p.Xa=!1;p.Bb=!1;p.i=i;p.g=i;p.Na=i;p.sa=i;p.vb=i;p.Ma=i;p.xa=i;p.w=i;function $c(a,b){a.wb=b;a.sa&&sc(a.sa,b)}function ad(a,b){a.Qa=b;if(a.xa)a.xa.innerHTML=b}
p.m=function(){if(this.Wa&&this.Ja&&!this.g)this.g=this.r().m("iframe",{frameborder:0,style:"border:0;vertical-align:bottom;",src:'javascript:""'}),this.g.className=this.t+"-bg",F(this.g,!1),Rc(this.g,0);else if((!this.Wa||!this.Ja)&&this.g)qc(this.g),this.g=i;if(this.Ja&&!this.i)this.i=this.r().m("div",this.t+"-bg"),Rc(this.i,this.yb),F(this.i,!1);else if(!this.Ja&&this.i)qc(this.i),this.i=i;var a=this.r();this.c=a.m("div",{className:this.t,tabIndex:0},this.Na=a.m("div",{className:this.t+"-title",
id:this.Fa||(this.Fa=":"+(this.jb.nb++).toString(36))},this.sa=a.m("span",this.t+"-title-text",this.wb),this.Ma=a.m("span",this.t+"-title-close")),this.xa=a.m("div",this.t+"-content"),this.w=a.m("div",this.t+"-buttons"),this.ub=a.m("span",{tabIndex:0}));this.vb=this.Na.id;vc(this.e());this.e().setAttribute("aria-labelledby",this.vb||"");if(this.Qa)this.xa.innerHTML=this.Qa;F(this.Ma,this.hb);F(this.e(),!1);if(this.s)a=this.s,a.c=this.w,a.ga()};
p.ga=function(a){this.G&&c(Error("Component already rendered"));this.e()||this.m();a=a||tc(this.r()).body;this.g&&a.appendChild(this.g);this.i&&a.appendChild(this.i);Wc.j.ga.call(this,a)};p.Ba=function(){Wc.j.Ba.call(this);this.Ca=new wc(tc(this.r()));if(this.cb&&!this.$){var a=new Ac(this.e(),this.Na);ac(this.Na,this.t+"-title-draggable");this.$=a}E(E(this.aa(),this.Ma,"click",this.Pb),this.Ca,"focusin",this.Nb);vc(this.e());this.sa.id!==""&&this.e().setAttribute("aria-labelledby",this.sa.id)};
p.na=function(){this.Xa&&bd(this,!1);this.Ca.o();this.Ca=i;if(this.$)this.$.o(),this.$=i;Wc.j.na.call(this)};
function bd(a,b){if(b!=a.Xa){var d=tc(a.r()),e=(d?d.parentWindow||d.defaultView:window)||window;a.G||a.ga(d.body);if(b){cd(a);d=((d=tc(a.r()))?d.parentWindow||d.defaultView:window)||window;if((Nc(a.e(),"position")||(a.e().currentStyle?a.e().currentStyle.position:i)||a.e().style.position)=="fixed")var f=0,h=0;else h=uc(a.r()),f=h.x,h=h.y;var j=Qc(a.e()),k=jc(d||window),d=a.e(),f=Math.max(f+k.width/2-j.width/2,0),k=Math.max(h+k.height/2-j.height/2,0),j=Wa&&(Fa||Za)&&z("1.9");f instanceof bc?(h=f.x,
f=f.y):(h=f,f=k);d.style.left=Pc(h,j);d.style.top=Pc(f,j);E(E(E(a.aa(),a.e(),"keydown",a.Ka),a.e(),"keypress",a.Ka),e,"resize",a.pb)}else Vb(Vb(Vb(a.aa(),a.e(),"keydown",a.Ka),a.e(),"keypress",a.Ka),e,"resize",a.pb);a.g&&F(a.g,b);a.i&&F(a.i,b);F(a.e(),b);b&&a.focus();(a.Xa=b)?E(a.aa(),a.w,"click",a.ob):(Vb(a.aa(),a.w,"click",a.ob),a.dispatchEvent(dd),a.Bb&&a.o())}}
p.focus=function(){try{this.e().focus()}catch(a){}if(this.s){var b=this.s.ya;if(b)for(var d=tc(this.r()),e=this.w.getElementsByTagName("button"),f=0,h;h=e[f];f++)if(h.name==b){try{if(y||Va){var j=d.createElement("input");j.style.cssText="position:fixed;width:0;height:0;left:0;top:0;";this.e().appendChild(j);j.focus();this.e().removeChild(j)}h.focus()}catch(k){}break}}};
function cd(a){a.g&&F(a.g,!1);a.i&&F(a.i,!1);var b=tc(a.r()),d=jc((b?b.parentWindow||b.defaultView:window)||window||window),e=Math.max(b.body.scrollWidth,d.width),b=Math.max(b.body.scrollHeight,d.height);a.g&&(F(a.g,!0),Oc(a.g,e,b));a.i&&(F(a.i,!0),Oc(a.i,e,b));if(a.cb)d=Qc(a.e()),a.$.Ta=new zc(0,0,e-d.width,b-d.height)}p.Pb=function(){if(this.hb){var a=this.s,b=a&&a.Pa;b?(a=a.get(b),this.dispatchEvent(new ed(b,a))&&bd(this,!1)):bd(this,!1)}};
p.h=function(){Wc.j.h.call(this);if(this.i)qc(this.i),this.i=i;if(this.g)qc(this.g),this.g=i;this.ub=this.w=this.Ma=i};function fd(a){var b=G(new Xc,gd,!0);a.s=b;if(a.w)a.s?(b=a.s,b.c=a.w,b.ga()):a.w.innerHTML=""}p.ob=function(a){a:{for(a=a.target;a!=i&&a!=this.w;){if(a.tagName=="BUTTON")break a;a=a.parentNode}a=i}if(a&&!a.disabled){var a=a.name,b=this.s.get(a);this.dispatchEvent(new ed(a,b))&&bd(this,!1)}};
p.Ka=function(a){var b=!1,d=!1,e=this.s,f=a.target;if(a.type=="keydown")if(this.Cb&&a.keyCode==27){var h=e&&e.Pa,f=f.tagName=="SELECT"&&!f.disabled;h&&!f?(d=!0,b=e.get(h),b=this.dispatchEvent(new ed(h,b))):f||(b=!0)}else a.keyCode==9&&a.shiftKey&&f==this.e()&&(d=!0);else if(a.keyCode==13){if(f.tagName=="BUTTON")h=f.name;else if(e){var j=e.ya,k;if(k=j)a:{k=e.c.getElementsByTagName("BUTTON");for(var n=0,o;o=k[n];n++)if(o.name==j||o.id==j){k=o;break a}k=i}f=(f.tagName=="TEXTAREA"||f.tagName=="SELECT")&&
!f.disabled;k&&!k.disabled&&!f&&(h=j)}h&&(d=!0,b=this.dispatchEvent(new ed(h,String(e.get(h)))))}if(b||d)a.stopPropagation(),a.preventDefault();b&&bd(this,!1)};p.pb=function(){cd(this)};p.Nb=function(a){if(this.ub==a.target)a=this.Db,ea(a)?this&&(a=la(a,this)):a&&typeof a.handleEvent=="function"?a=la(a.handleEvent,a):c(Error("Invalid listener argument")),Yb.setTimeout(a,0)};p.Db=function(){x&&tc(this.r()).body.focus();this.e().focus()};function ed(a,b){this.type=hd;this.key=a;this.caption=b}
w(ed,jb);var hd="dialogselect",dd="afterhide";function Xc(a){this.za=a||dc();Lc.call(this)}w(Xc,Lc);p=Xc.prototype;p.t="goog-buttonset";p.ya=i;p.c=i;p.Pa=i;p.set=function(a,b,d,e){Lc.prototype.set.call(this,a,b);if(d)this.ya=a;if(e)this.Pa=a;return this};function G(a,b,d,e){return a.set(b.key,b.caption,d,e)}p.ga=function(){if(this.c){this.c.innerHTML="";var a=dc(this.c);Kc(this,function(b,d){var e=a.m("button",{name:d},b);if(d==this.ya)e.className=this.t+"-default";this.c.appendChild(e)},this)}};
var id=na("OK"),jd=na("Cancel"),kd=na("Yes"),ld=na("No"),md=na("Save"),nd=na("Continue"),Yc={key:"ok",caption:id},Zc={key:"cancel",caption:jd},od={key:"yes",caption:kd},pd={key:"no",caption:ld},qd={key:"save",caption:md},gd={key:"continue",caption:nd};G(new Xc,Yc,!0,!0);G(G(new Xc,Yc,!0),Zc,!1,!0);G(G(new Xc,od,!0),pd,!1,!0);G(G(G(new Xc,od),pd,!0),Zc,!1,!0);G(G(G(new Xc,gd),qd),Zc,!0,!0);function rd(a,b){if(a)this.Ha&&this.detach(),this.c=a,this.Ga=C(this.c,"keypress",this,b),this.Sa=C(this.c,"keydown",this.Eb,b,this),this.Ha=C(this.c,"keyup",this.Fb,b,this)}w(rd,Xb);p=rd.prototype;p.c=i;p.Ga=i;p.Sa=i;p.Ha=i;p.O=-1;p.M=-1;
var sd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},td={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},ud={61:187,59:186},vd=x||y&&z("525");p=rd.prototype;
p.Eb=function(a){if(y&&(this.O==17&&!a.ctrlKey||this.O==18&&!a.altKey))this.M=this.O=-1;vd&&!xc(a.keyCode,this.O,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):this.M=Wa&&a.keyCode in ud?ud[a.keyCode]:a.keyCode};p.Fb=function(){this.M=this.O=-1};
p.handleEvent=function(a){var b=a.q,d,e;x&&a.type=="keypress"?(d=this.M,e=d!=13&&d!=27?b.keyCode:0):y&&a.type=="keypress"?(d=this.M,e=b.charCode>=0&&b.charCode<63232&&yc(d)?b.charCode:0):Va?(d=this.M,e=yc(d)?b.keyCode:0):(d=b.keyCode||this.M,e=b.charCode||0,Fa&&e==63&&!d&&(d=191));var f=d,h=b.keyIdentifier;d?d>=63232&&d in sd?f=sd[d]:d==25&&a.shiftKey&&(f=9):h&&h in td&&(f=td[h]);a=f==this.O;this.O=f;b=new wd(f,e,a,b);try{this.dispatchEvent(b)}finally{b.o()}};p.e=l("c");
p.detach=function(){if(this.Ga)D(this.Ga),D(this.Sa),D(this.Ha),this.Ha=this.Sa=this.Ga=i;this.c=i;this.M=this.O=-1};p.h=function(){rd.j.h.call(this);this.detach()};function wd(a,b,d,e){e&&this.R(e,g);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=d}w(wd,mb);function H(a){return a!=i&&a!==!1}function xd(a,b){var d=a[r.call(i,b)];return H(d)?d:(d=a._,H(d)?d:!1)}function yd(a){return Array.prototype.slice.call(a)}function zd(a){return Array.prototype.slice.call(arguments)}
var I=function Ad(b){return H(H(b)?b.V:b)?b.V(b):function(){var d=Ad[r.call(i,b)];return H(d)?d:Ad._}().call(i,b)},Cd=function Bd(b,d){return H(H(b)?b.H:b)?b.H(b,d):function(){var d=Bd[r.call(i,b)];return H(d)?d:Bd._}().call(i,b,d)},J=function(){function a(a,b,h){return H(H(a)?a.va:a)?a.va(a,b,h):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b,h)}function b(a,b){return H(H(a)?a.va:a)?a.va(a,b):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,
f,h){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}c("Invalid arity: "+arguments.length)}}(),Dd={},Fd=function Ed(b){return H(H(b)?b.X:b)?b.X(b):function(){var d=Ed[r.call(i,b)];return H(d)?d:Ed._}().call(i,b)},Hd=function Gd(b){return H(H(b)?b.Y:b)?b.Y(b):function(){var d=Gd[r.call(i,b)];return H(d)?d:Gd._}().call(i,b)},K=function(){function a(a,b,h){return H(H(a)?a.W:a)?a.W(a,b,h):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b,h)}function b(a,
b){return H(H(a)?a.W:a)?a.W(a,b):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,f,h){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}c("Invalid arity: "+arguments.length)}}(),Jd=function Id(b,d,e){return H(H(b)?b.ua:b)?b.ua(b,d,e):function(){var d=Id[r.call(i,b)];return H(d)?d:Id._}().call(i,b,d,e)},Kd={},Md=function Ld(b){return H(H(b)?b.wa:b)?b.wa(b):function(){var d=Ld[r.call(i,b)];return H(d)?d:Ld._}().call(i,
b)},Nd={},Pd=function Od(b){return H(H(b)?b.zb:b)?b.state:function(){var d=Od[r.call(i,b)];return H(d)?d:Od._}().call(i,b)},Qd={},Sd=function Rd(b){return H(H(b)?b.J:b)?b.f:function(){var d=Rd[r.call(i,b)];return H(d)?d:Rd._}().call(i,b)},Ud=function Td(b,d){return H(H(b)?b.K:b)?b.K(b,d):function(){var d=Td[r.call(i,b)];return H(d)?d:Td._}().call(i,b,d)},Vd=function(){function a(a,b,h){return H(H(a)?a.ja:a)?a.ja(a,b,h):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b,h)}function b(a,
b){return H(H(a)?a.ja:a)?a.ja(a,b):function(){var b=d[r.call(i,a)];return H(b)?b:d._}().call(i,a,b)}var d=i;return d=function(d,f,h){switch(arguments.length){case 2:return b.call(this,d,f);case 3:return a.call(this,d,f,h)}c("Invalid arity: "+arguments.length)}}(),Xd=function Wd(b,d){return H(H(b)?b.n:b)?b.n(b,d):function(){var d=Wd[r.call(i,b)];return H(d)?d:Wd._}().call(i,b,d)},Zd=function Yd(b){return H(H(b)?b.I:b)?b.I(b):function(){var d=Yd[r.call(i,b)];return H(d)?d:Yd._}().call(i,b)},ae=function $d(b){return H(H(b)?
b.D:b)?b.D(b):function(){var d=$d[r.call(i,b)];return H(d)?d:$d._}().call(i,b)},be={},ce={},ee=function de(b,d){return H(H(b)?b.z:b)?b.z(b,d):function(){var d=de[r.call(i,b)];return H(d)?d:de._}().call(i,b,d)};function fe(a,b){return a===b}function L(a,b){return Xd.call(i,a,b)}function M(a){return fe.call(i,a,i)}Xd["null"]=function(a,b){return M.call(i,b)};Cd["null"]=function(a,b){return N.call(i,b)};Dd["null"]=!0;Fd["null"]=m(i);Hd["null"]=function(){return N.call(i)};Md["null"]=m(i);
Ud["null"]=m(i);Kd["null"]=!0;J["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();Qd["null"]=!0;Sd["null"]=m(i);Vd["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return b.call(i);case 3:return d}c("Invalid arity: "+arguments.length)}}();Zd["null"]=m(0);I["null"]=m(0);Jd["null"]=function(a,b,d){return ge.call(i,b,d)};
K["null"]=function(){return function(a,b,d){switch(arguments.length){case 2:return i;case 3:return d}c("Invalid arity: "+arguments.length)}}();q.Date.prototype.n=function(a,b){return fe.call(i,a.toString,b.toString)};Zd.number=aa();Xd.number=function(a,b){return fe.call(i,a,b)};Zd["function"]=function(a){return ga.call(i,a)};function O(a){return a+1}function he(a,b){return a<b}
var ie=function(){return function(a,b,d,e){switch(arguments.length){case 2:var f;a:if(H(L.call(i,0,I.call(i,a))))f=b.call(i);else for(var h=J.call(i,a,0),j=1;;)if(H(he.call(i,j,I.call(i,a))))h=b.call(i,h,J.call(i,a,j)),j=O.call(i,j);else{f=h;break a}return f;case 3:a:{f=d;for(j=0;;)if(H(he.call(i,j,I.call(i,a))))f=b.call(i,f,J.call(i,a,j)),j=O.call(i,j);else{h=f;break a}}return h;case 4:a:{f=d;for(h=e;;)if(H(he.call(i,h,I.call(i,a))))f=b.call(i,f,J.call(i,a,h)),h=O.call(i,h);else{j=f;break a}}return j}c("Invalid arity: "+
arguments.length)}}();function je(a,b){this.U=a;this.ca=b}p=je.prototype;p.ja=function(){return function(a,b,d){switch(arguments.length){case 2:return ie.call(i,this.U,b,this.U[this.ca],O.call(i,this.ca));case 3:return ie.call(i,this.U,b,d,this.ca)}c("Invalid arity: "+arguments.length)}}();p.n=function(a,b){return ke.call(i,a,b)};p.Z=!0;p.ka=!0;p.X=function(){return this.U[this.ca]};p.Y=function(){return H(he.call(i,O.call(i,this.ca),I.call(i,this.U)))?new je(this.U,O.call(i,this.ca)):N.call(i)};
p.D=aa();function le(a,b){return H(L.call(i,0,I.call(i,a)))?i:new je(a,b)}function Q(a,b){return le.call(i,a,b)}Vd.array=function(){return function(a,b,d){switch(arguments.length){case 2:return ie.call(i,a,b);case 3:return ie.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();K.array=function(){return function(a,b,d){switch(arguments.length){case 2:return a[b];case 3:return J.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
J.array=function(){return function(a,b,d){switch(arguments.length){case 2:return H(he.call(i,b,a.length))?a[b]:i;case 3:return H(he.call(i,b,a.length))?a[b]:d}c("Invalid arity: "+arguments.length)}}();I.array=function(a){return a.length};ae.array=function(a){return Q.call(i,a,0)};function R(a){return H(a)?ae.call(i,a):i}function S(a){a=R.call(i,a);return H(a)?Fd.call(i,a):i}function T(a){return Hd.call(i,R.call(i,a))}function U(a){return H(a)?R.call(i,T.call(i,a)):i}
function me(a){return S.call(i,U.call(i,a))}function ne(a){return U.call(i,U.call(i,a))}I._=function(a){for(var a=R.call(i,a),b=0;;)if(H(a))a=U.call(i,a),b=O.call(i,b);else return b};Xd._=function(a,b){return fe.call(i,a,b)};function oe(a){return H(a)?!1:!0}
var pe=function(){var a=i,b=function(){function b(a,d,j){var k=i;s(j)&&(k=Q(Array.prototype.slice.call(arguments,2),0));return e.call(this,a,d,k)}function e(b,d,e){for(;;)if(H(e))b=a.call(i,b,d),d=S.call(i,e),e=U.call(i,e);else return a.call(i,b,d)}b.b=2;b.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 2:return Cd.call(i,a,e);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=
b.a;return a}();function qe(a){return I.call(i,a)}
var re=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,a,b);case 3:return K.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}(),se=function(){var a=i,b=function(){function b(a,d,j,k){var n=i;s(k)&&(n=Q(Array.prototype.slice.call(arguments,3),0));return e.call(this,a,d,j,n)}function e(b,d,e,k){for(;;)if(b=a.call(i,b,d,e),H(k))d=S.call(i,k),e=me.call(i,k),k=ne.call(i,k);else return b}b.b=3;b.a=function(a){var b=S(a),d=S(U(a)),k=S(U(U(a))),a=T(U(U(a)));return e.call(this,
b,d,k,a)};return b}(),a=function(a,e,f,h){switch(arguments.length){case 3:return Jd.call(i,a,e,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=3;a.a=b.a;return a}();function te(a,b){return Ud.call(i,a,b)}function ue(a){return H(H(H(a)?a.B:a)?!0:xd.call(i,Qd,a))?Sd.call(i,a):i}function ve(a){return Md.call(i,a)}function we(a){return Zd.call(i,a)}function xe(a){return H(H(a)?a.Z:a)?!0:xd.call(i,be,a)}
function ye(a){return H(M.call(i,a))?!1:H(H(a)?a.Za:a)?!0:xd.call(i,Kd,a)}function ze(a){return H(H(a)?a.Ab:a)?!0:xd.call(i,Nd,a)}function Ae(a){var b=zd.call(i);Db.call(i,a,function(a,e){return b.push(e)});return b}function Be(a){return g===a}function Ce(a){return H(M.call(i,a))?!1:H(H(a)?a.ka:a)?!0:xd.call(i,Dd,a)}function De(a){return H(a)?!0:!1}
function Ee(a){var b=u.call(i,a);return H(b)?oe.call(i,function(){var b=L.call(i,a.charAt(0),"\ufdd0");return H(b)?b:L.call(i,a.charAt(0),"\ufdd1")}()):b}function Fe(a){var b=u.call(i,a);return H(b)?L.call(i,a.charAt(0),"\ufdd0"):b}function Ge(a){var b=u.call(i,a);return H(b)?L.call(i,a.charAt(0),"\ufdd1"):b}
var V=function(){return function(a,b,d){switch(arguments.length){case 2:return Vd.call(i,b,a);case 3:return Vd.call(i,d,a,b)}c("Invalid arity: "+arguments.length)}}(),He=function(){return function(a,b,d){switch(arguments.length){case 2:var e=R.call(i,b);return H(e)?V.call(i,a,S.call(i,e),U.call(i,e)):a.call(i);case 3:a:for(var f=b,h=R.call(i,d);;)if(H(h))f=a.call(i,f,S.call(i,h)),h=U.call(i,h);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();
Vd._=function(){return function(a,b,d){switch(arguments.length){case 2:return He.call(i,b,a);case 3:return He.call(i,b,d,a)}c("Invalid arity: "+arguments.length)}}();
var Ie=function(){var a=i,b=function(){function b(d,f,h){var j=i;s(h)&&(j=Q(Array.prototype.slice.call(arguments,2),0));return V.call(i,a,a.call(i,d,f),j)}b.b=2;b.a=function(b){var d=S(b),h=S(U(b)),b=T(U(b));return V.call(i,a,a.call(i,d,h),b)};return b}(),a=function(a,e,f){switch(arguments.length){case 0:return 0;case 1:return a;case 2:return a+e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Je=function(){var a=i,b=function(){function b(d,
f,h){var j=i;s(h)&&(j=Q(Array.prototype.slice.call(arguments,2),0));return V.call(i,a,a.call(i,d,f),j)}b.b=2;b.a=function(b){var d=S(b),h=S(U(b)),b=T(U(b));return V.call(i,a,a.call(i,d,h),b)};return b}(),a=function(a,e,f){switch(arguments.length){case 1:return-a;case 2:return a-e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Ke=function(){var a=i,b=function(){function b(d,f,h){var j=i;s(h)&&(j=Q(Array.prototype.slice.call(arguments,2),0));
return V.call(i,a,a.call(i,d,f),j)}b.b=2;b.a=function(b){var d=S(b),h=S(U(b)),b=T(U(b));return V.call(i,a,a.call(i,d,h),b)};return b}(),a=function(a,e,f){switch(arguments.length){case 0:return 1;case 1:return a;case 2:return a*e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Le=function(){var a=i,b=function(){function b(a,d,j){var k=i;s(j)&&(k=Q(Array.prototype.slice.call(arguments,2),0));return e.call(this,a,d,k)}function e(b,d,e){for(;;)if(H(a.call(i,
b,d)))if(H(U.call(i,e)))b=d,d=S.call(i,e),e=U.call(i,e);else return a.call(i,d,S.call(i,e));else return!1}b.b=2;b.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Me=function(){var a=i,b=function(){function b(a,d,j){var k=i;s(j)&&(k=Q(Array.prototype.slice.call(arguments,2),0));return e.call(this,
a,d,k)}function e(b,d,e){for(;;)if(H(a.call(i,b,d)))if(H(U.call(i,e)))b=d,d=S.call(i,e),e=U.call(i,e);else return a.call(i,d,S.call(i,e));else return!1}b.b=2;b.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Ne=function(){var a=i,b=function(){function b(a,d,j){var k=i;s(j)&&(k=Q(Array.prototype.slice.call(arguments,
2),0));return e.call(this,a,d,k)}function e(b,d,e){for(;;)if(H(a.call(i,b,d)))if(H(U.call(i,e)))b=d,d=S.call(i,e),e=U.call(i,e);else return a.call(i,d,S.call(i,e));else return!1}b.b=2;b.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}(),Oe=function(){var a=i,b=function(){function b(a,d,
j){var k=i;s(j)&&(k=Q(Array.prototype.slice.call(arguments,2),0));return e.call(this,a,d,k)}function e(b,d,e){for(;;)if(H(a.call(i,b,d)))if(H(U.call(i,e)))b=d,d=S.call(i,e),e=U.call(i,e);else return a.call(i,d,S.call(i,e));else return!1}b.b=2;b.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return e.call(this,b,d,a)};return b}(),a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}();
function Pe(a){return Je.call(i,a,1)}function Qe(a){return H(Oe.call(i,a,0))?Math.floor.call(i,a):Math.ceil.call(i,a)}var Re=function(){var a=i;return a=function(b){switch(arguments.length){case 0:return Math.random.call(i);case 1:return Ke.call(i,b,a.call(i))}c("Invalid arity: "+arguments.length)}}();function Se(a){return Qe.call(i,Re.call(i,a))}function Te(a,b){return a^b}function Ue(a,b){return a<<b}function Ve(a,b){return a>>b}function We(a){return Le.call(i,0,a)}
function Xe(a,b){for(var d=b,e=R.call(i,a);;)if(H(function(){var a=e;return H(a)?We.call(i,d):a}()))var f=Pe.call(i,d),h=U.call(i,e),d=f,e=h;else return e}J._=function(){return function(a,b,d){switch(arguments.length){case 2:var e;var f=Xe.call(i,a,b);H(f)?e=S.call(i,f):c("Index out of bounds");return e;case 3:return e=Xe.call(i,a,b),H(e)?S.call(i,e):d}c("Invalid arity: "+arguments.length)}}();
var Ye=function(){var a=i,b=function(){function b(a,d){var j=i;s(d)&&(j=Q(Array.prototype.slice.call(arguments,1),0));return e.call(this,a,j)}function e(b,d){return function(b,d){for(;;)if(H(d))var e=b.append(a.call(i,S.call(i,d))),f=U.call(i,d),b=e,d=f;else return a.call(i,b)}.call(i,new Ia(a.call(i,b)),d)}b.b=1;b.a=function(a){var b=S(a),a=T(a);return e.call(this,b,a)};return b}(),a=function(a,e){switch(arguments.length){case 0:return"";case 1:return H(M.call(i,a))?"":a.toString();default:return b.apply(this,
arguments)}c("Invalid arity: "+arguments.length)};a.b=1;a.a=b.a;return a}(),Ze=function(){return function(a,b,d){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,d)}c("Invalid arity: "+arguments.length)}}();
function ke(a,b){return De.call(i,H(xe.call(i,b))?function(){for(var d=R.call(i,a),e=R.call(i,b);;)if(H(M.call(i,d)))return M.call(i,e);else if(H(M.call(i,e)))return!1;else if(H(L.call(i,S.call(i,d),S.call(i,e))))d=U.call(i,d),e=U.call(i,e);else return H("\ufdd0'else")?!1:i}():i)}function $e(a,b){return Te.call(i,a,Ie.call(i,b,2654435769,Ue.call(i,a,6),Ve.call(i,a,2)))}function af(a){return V.call(i,function(a,d){return $e.call(i,a,we.call(i,d))},we.call(i,S.call(i,a)),U.call(i,a))}
function bf(a,b,d,e){this.f=a;this.oa=b;this.ha=d;this.count=e}p=bf.prototype;p.n=function(a,b){return ke.call(i,a,b)};p.H=function(a,b){return new bf(this.f,b,a,O.call(i,this.count))};p.ka=!0;p.X=l("oa");p.Y=l("ha");p.D=aa();p.wa=function(a){return Hd.call(i,a)};p.K=function(a,b){return new bf(b,this.oa,this.ha,this.count)};p.B=!0;p.J=l("f");p.I=function(a){return af.call(i,a)};p.V=l("count");p.Z=!0;function cf(a){this.f=a}p=cf.prototype;p.n=function(a,b){return ke.call(i,a,b)};
p.H=function(a,b){return new bf(this.f,b,i,1)};p.ka=!0;p.X=m(i);p.Y=m(i);p.D=m(i);p.wa=m(i);p.K=function(a,b){return new cf(b)};p.B=!0;p.J=l("f");p.I=function(a){return af.call(i,a)};p.V=m(0);p.Z=!0;var df=new cf(i);function ef(a){return V.call(i,pe,df,a)}var N=function(){function a(a){var d=i;s(a)&&(d=Q(Array.prototype.slice.call(arguments,0),0));return V.call(i,pe,df,ef.call(i,d))}a.b=0;a.a=function(a){a=R(a);return V.call(i,pe,df,ef.call(i,a))};return a}();
function ff(a,b,d){this.f=a;this.oa=b;this.ha=d}p=ff.prototype;p.D=aa();p.I=function(a){return af.call(i,a)};p.n=function(a,b){return ke.call(i,a,b)};p.Z=!0;p.H=function(a,b){return new ff(i,b,a)};p.ka=!0;p.X=l("oa");p.Y=function(){return H(M.call(i,this.ha))?df:this.ha};p.B=!0;p.J=l("f");p.K=function(a,b){return new ff(b,this.oa,this.ha)};function W(a,b){return new ff(i,a,b)}
Vd.string=function(){return function(a,b,d){switch(arguments.length){case 2:return ie.call(i,a,b);case 3:return ie.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();K.string=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b);case 3:return J.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
J.string=function(){return function(a,b,d){switch(arguments.length){case 2:return H(Le.call(i,b,I.call(i,a)))?a.charAt(b):i;case 3:return H(Le.call(i,b,I.call(i,a)))?a.charAt(b):d}c("Invalid arity: "+arguments.length)}}();I.string=function(a){return a.length};ae.string=function(a){return le.call(i,a,0)};Zd.string=function(a){return za.call(i,a)};
q.String.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return re.call(i,b,this.toString());case 3:return re.call(i,b,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();q.String.prototype.apply=function(a,b){return H(Le.call(i,qe.call(i,b),2))?this.call(i,b[0]):this.call(i,b[0],b[1])};function gf(a){var b=a.x;return H(a.Ua)?b:(a.x=b.call(i),a.Ua=!0,a.x)}function X(a,b,d){this.f=a;this.Ua=b;this.x=d}p=X.prototype;
p.D=function(a){return R.call(i,gf.call(i,a))};p.I=function(a){return af.call(i,a)};p.n=function(a,b){return ke.call(i,a,b)};p.Z=!0;p.H=function(a,b){return W.call(i,b,a)};p.ka=!0;p.X=function(a){return S.call(i,gf.call(i,a))};p.Y=function(a){return T.call(i,gf.call(i,a))};p.B=!0;p.J=l("f");p.K=function(a,b){return new X(b,this.Ua,this.x)};function hf(a){for(var b=zd.call(i);;)if(H(R.call(i,a)))b.push(S.call(i,a)),a=U.call(i,a);else return b}
function jf(a,b){for(var d=a,e=b,f=0;;)if(H(function(){var a=We.call(i,e);return H(a)?R.call(i,d):a}()))var h=U.call(i,d),j=Pe.call(i,e),f=O.call(i,f),d=h,e=j;else return f}
var lf=function kf(b){return H(M.call(i,b))?i:H(M.call(i,U.call(i,b)))?R.call(i,S.call(i,b)):H("\ufdd0'else")?W.call(i,S.call(i,b),kf.call(i,U.call(i,b))):i},mf=function(){function a(a,b){return new X(i,!1,function(){var d=R.call(i,a);return H(d)?W.call(i,S.call(i,d),e.call(i,T.call(i,d),b)):b})}function b(a){return new X(i,!1,function(){return a})}function d(){return new X(i,!1,m(i))}var e=i,f=function(){function a(d,e,f){var h=i;s(f)&&(h=Q(Array.prototype.slice.call(arguments,2),0));return b.call(this,
d,e,h)}function b(a,d,f){return function t(a,b){return new X(i,!1,function(){var d=R.call(i,a);return H(d)?W.call(i,S.call(i,d),t.call(i,T.call(i,d),b)):H(b)?t.call(i,S.call(i,b),U.call(i,b)):i})}.call(i,e.call(i,a,d),f)}a.b=2;a.a=function(a){var d=S(a),e=S(U(a)),a=T(U(a));return b.call(this,d,e,a)};return a}(),e=function(e,j,k){switch(arguments.length){case 0:return d.call(this);case 1:return b.call(this,e);case 2:return a.call(this,e,j);default:return f.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};e.b=2;e.a=f.a;return e}(),nf=function(){var a=i,b=function(){function a(d,h,j,k,n){var o=i;s(n)&&(o=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,d,h,j,k,o)}function b(a,d,e,k,n){return W.call(i,a,W.call(i,d,W.call(i,e,W.call(i,k,lf.call(i,n)))))}a.b=4;a.a=function(a){var d=S(a),j=S(U(a)),k=S(U(U(a))),n=S(U(U(U(a)))),a=T(U(U(U(a))));return b.call(this,d,j,k,n,a)};return a}(),a=function(a,e,f,h,j){switch(arguments.length){case 1:return R.call(i,a);case 2:return W.call(i,
a,e);case 3:return W.call(i,a,W.call(i,e,f));case 4:return W.call(i,a,W.call(i,e,W.call(i,f,h)));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=4;a.a=b.a;return a}(),of=function(){var a=i,b=function(){function a(d,h,j,k,n,o){var v=i;s(o)&&(v=Q(Array.prototype.slice.call(arguments,5),0));return b.call(this,d,h,j,k,n,v)}function b(a,d,e,k,n,o){d=W.call(i,d,W.call(i,e,W.call(i,k,W.call(i,n,lf.call(i,o)))));e=a.b;return H(a.a)?H(Me.call(i,jf.call(i,d,e),e))?a.apply(a,
hf.call(i,d)):a.a(d):a.apply(a,hf.call(i,d))}a.b=5;a.a=function(a){var d=S(a),j=S(U(a)),k=S(U(U(a))),n=S(U(U(U(a)))),o=S(U(U(U(U(a))))),a=T(U(U(U(U(a)))));return b.call(this,d,j,k,n,o,a)};return a}(),a=function(a,e,f,h,j,k){switch(arguments.length){case 2:var n=a,o=e,v=n.b;return H(n.a)?H(Me.call(i,jf.call(i,o,O.call(i,v)),v))?n.apply(n,hf.call(i,o)):n.a(o):n.apply(n,hf.call(i,o));case 3:return n=a,o=nf.call(i,e,f),v=n.b,H(n.a)?H(Me.call(i,jf.call(i,o,v),v))?n.apply(n,hf.call(i,o)):n.a(o):n.apply(n,
hf.call(i,o));case 4:return n=a,o=nf.call(i,e,f,h),v=n.b,H(n.a)?H(Me.call(i,jf.call(i,o,v),v))?n.apply(n,hf.call(i,o)):n.a(o):n.apply(n,hf.call(i,o));case 5:return n=a,o=nf.call(i,e,f,h,j),v=n.b,H(n.a)?H(Me.call(i,jf.call(i,o,v),v))?n.apply(n,hf.call(i,o)):n.a(o):n.apply(n,hf.call(i,o));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=5;a.a=b.a;return a}();
function pf(a,b){for(;;)if(H(M.call(i,R.call(i,b))))return!0;else if(H(a.call(i,S.call(i,b))))var d=a,e=U.call(i,b),a=d,b=e;else return H("\ufdd0'else")?!1:i}function qf(a){return a}
var rf=function(){function a(a,b,d,f){return new X(i,!1,function(){var o=R.call(i,b),v=R.call(i,d),t=R.call(i,f);return H(H(o)?H(v)?t:v:o)?W.call(i,a.call(i,S.call(i,o),S.call(i,v),S.call(i,t)),e.call(i,a,T.call(i,o),T.call(i,v),T.call(i,t))):i})}function b(a,b,d){return new X(i,!1,function(){var f=R.call(i,b),o=R.call(i,d);return H(H(f)?o:f)?W.call(i,a.call(i,S.call(i,f),S.call(i,o)),e.call(i,a,T.call(i,f),T.call(i,o))):i})}function d(a,b){return new X(i,!1,function(){var d=R.call(i,b);return H(d)?
W.call(i,a.call(i,S.call(i,d)),e.call(i,a,T.call(i,d))):i})}var e=i,f=function(){function a(d,e,f,h,t){var P=i;s(t)&&(P=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,d,e,f,h,P)}function b(a,d,f,h,j){return e.call(i,function(b){return of.call(i,a,b)},function Z(a){return new X(i,!1,function(){var b=e.call(i,R,a);return H(pf.call(i,qf,b))?W.call(i,e.call(i,S,b),Z.call(i,e.call(i,T,b))):i})}.call(i,pe.call(i,j,h,f,d)))}a.b=4;a.a=function(a){var d=S(a),e=S(U(a)),f=S(U(U(a))),h=S(U(U(U(a)))),
a=T(U(U(U(a))));return b.call(this,d,e,f,h,a)};return a}(),e=function(e,j,k,n,o){switch(arguments.length){case 2:return d.call(this,e,j);case 3:return b.call(this,e,j,k);case 4:return a.call(this,e,j,k,n);default:return f.apply(this,arguments)}c("Invalid arity: "+arguments.length)};e.b=4;e.a=f.a;return e}(),tf=function sf(b,d){return new X(i,!1,function(){if(H(We.call(i,b))){var e=R.call(i,d);return H(e)?W.call(i,S.call(i,e),sf.call(i,Pe.call(i,b),T.call(i,e))):i}else return i})};
function uf(a,b){function d(a,b){for(;;){var d=R.call(i,b);if(H(function(){var b=We.call(i,a);return H(b)?d:b}()))var j=Pe.call(i,a),k=T.call(i,d),a=j,b=k;else return d}}return new X(i,!1,function(){return d.call(i,a,b)})}
var vf=function(){function a(a){return new X(i,!1,function(){return W.call(i,a,b.call(i,a))})}var b=i;return b=function(d,e){switch(arguments.length){case 1:return a.call(this,d);case 2:return tf.call(i,d,b.call(i,e))}c("Invalid arity: "+arguments.length)}}(),wf=function(){function a(a,d){return new X(i,!1,function(){var h=R.call(i,a),j=R.call(i,d);return H(H(h)?j:h)?W.call(i,S.call(i,h),W.call(i,S.call(i,j),b.call(i,T.call(i,h),T.call(i,j)))):i})}var b=i,d=function(){function a(b,e,k){var n=i;s(k)&&
(n=Q(Array.prototype.slice.call(arguments,2),0));return d.call(this,b,e,n)}function d(a,e,f){return new X(i,!1,function(){var d=rf.call(i,R,pe.call(i,f,e,a));return H(pf.call(i,qf,d))?mf.call(i,rf.call(i,S,d),of.call(i,b,rf.call(i,T,d))):i})}a.b=2;a.a=function(a){var b=S(a),e=S(U(a)),a=T(U(a));return d.call(this,b,e,a)};return a}(),b=function(b,f,h){switch(arguments.length){case 2:return a.call(this,b,f);default:return d.apply(this,arguments)}c("Invalid arity: "+arguments.length)};b.b=2;b.a=d.a;return b}();
function xf(a,b){return uf.call(i,1,wf.call(i,vf.call(i,a),b))}function yf(a){return function d(a,f){return new X(i,!1,function(){var h=R.call(i,a);return H(h)?W.call(i,S.call(i,h),d.call(i,T.call(i,h),f)):H(R.call(i,f))?d.call(i,S.call(i,f),T.call(i,f)):i})}.call(i,i,a)}
var zf=function(){var a=i,b=function(){function a(b,d,h){var j=i;s(h)&&(j=Q(Array.prototype.slice.call(arguments,2),0));return yf.call(i,of.call(i,rf,b,d,j))}a.b=2;a.a=function(a){var b=S(a),d=S(U(a)),a=T(U(a));return yf.call(i,of.call(i,rf,b,d,a))};return a}(),a=function(a,e,f){switch(arguments.length){case 2:return yf.call(i,rf.call(i,a,e));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=2;a.a=b.a;return a}();function Af(a,b){return V.call(i,Cd,a,b)}
var Bf=function(){function a(a,b,h,j){return new X(i,!1,function(){var k=R.call(i,j);if(H(k)){var n=tf.call(i,a,k);return H(L.call(i,a,qe.call(i,n)))?W.call(i,n,d.call(i,a,b,h,uf.call(i,b,k))):N.call(i,tf.call(i,a,mf.call(i,n,h)))}else return i})}function b(a,b,h){return new X(i,!1,function(){var j=R.call(i,h);if(H(j)){var k=tf.call(i,a,j);return H(L.call(i,a,qe.call(i,k)))?W.call(i,k,d.call(i,a,b,uf.call(i,b,j))):i}else return i})}var d=i;return d=function(e,f,h,j){switch(arguments.length){case 2:return d.call(i,
e,e,f);case 3:return b.call(this,e,f,h);case 4:return a.call(this,e,f,h,j)}c("Invalid arity: "+arguments.length)}}();function Cf(a,b){this.f=a;this.k=b}p=Cf.prototype;p.n=function(a,b){return ke.call(i,a,b)};p.H=function(a,b){var d=yd.call(i,this.k);d.push(b);return new Cf(this.f,d)};p.D=function(){var a=this;return H(Ne.call(i,a.k.length,0))?function d(e){return new X(i,!1,function(){return H(Le.call(i,e,a.k.length))?W.call(i,a.k[e],d.call(i,O.call(i,e))):i})}.call(i,0):i};p.Ab=!0;
p.wa=function(){if(H(Ne.call(i,this.k.length,0))){var a=yd.call(i,this.k);a.pop();return new Cf(this.f,a)}else return i};p.K=function(a,b){return new Cf(b,this.k)};
p.va=function(){function a(a,b,f){var h=this;return H(function(){var a=Me.call(i,0,b);return H(a)?Le.call(i,b,h.k.length):a}())?h.k[b]:f}function b(a,b){var f=this;return H(function(){var a=Me.call(i,0,b);return H(a)?Le.call(i,b,f.k.length):a}())?f.k[b]:i}return function(d,e,f){switch(arguments.length){case 2:return b.call(this,0,e);case 3:return a.call(this,0,e,f)}c("Invalid arity: "+arguments.length)}}();p.B=!0;p.J=l("f");
p.ja=function(){return function(a,b,d){switch(arguments.length){case 2:return ie.call(i,this.k,b);case 3:return ie.call(i,this.k,b,d)}c("Invalid arity: "+arguments.length)}}();p.I=function(a){return af.call(i,a)};p.V=function(){return this.k.length};p.Z=!0;p.ua=function(a,b,d){a=yd.call(i,this.k);a[b]=d;return new Cf(this.f,a)};p.W=function(){return function(a,b,d){switch(arguments.length){case 2:return J.call(i,a,b,i);case 3:return J.call(i,a,b,d)}c("Invalid arity: "+arguments.length)}}();
var Df=new Cf(i,zd.call(i));function Ef(a){return new Cf(i,a)}Cf.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,this,b);case 3:return K.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Ff(a){return V.call(i,pe,Df,a)}var Gf=function(){function a(a){var d=i;s(a)&&(d=Q(Array.prototype.slice.call(arguments,0),0));return Ff.call(i,d)}a.b=0;a.a=function(a){a=R(a);return Ff.call(i,a)};return a}();function Hf(){}Hf.prototype.n=m(!1);
var If=new Hf;function Jf(a,b){return De.call(i,H(ye.call(i,b))?H(L.call(i,qe.call(i,a),qe.call(i,b)))?pf.call(i,qf,rf.call(i,function(a){return L.call(i,re.call(i,b,S.call(i,a),If),me.call(i,a))},a)):i:i)}function Kf(a,b,d){for(var e=d.length,f=0;;)if(H(Le.call(i,f,e)))if(H(L.call(i,b,d[f])))return f;else f=Ie.call(i,f,a);else return i}
var Lf=function(){function a(a,b,f,h){return H(function(){var f=u.call(i,a);return H(f)?b.hasOwnProperty(a):f}())?f:h}var b=i;return b=function(d,e,f,h){switch(arguments.length){case 2:return b.call(i,d,e,!0,!1);case 4:return a.call(this,d,e,f,h)}c("Invalid arity: "+arguments.length)}}();function Mf(a,b,d){this.f=a;this.keys=b;this.ra=d}p=Mf.prototype;p.n=function(a,b){return Jf.call(i,a,b)};p.H=function(a,b){return H(ze.call(i,b))?Jd.call(i,a,J.call(i,b,0),J.call(i,b,1)):V.call(i,Cd,a,b)};
p.D=function(){var a=this;return H(We.call(i,a.keys.length))?rf.call(i,function(b){return Gf.call(i,b,a.ra[b])},a.keys):i};p.K=function(a,b){return new Mf(b,this.keys,this.ra)};p.Za=!0;p.B=!0;p.J=l("f");p.I=function(a){return af.call(i,a)};p.V=function(){return this.keys.length};
p.ua=function(a,b,d){if(H(u.call(i,b))){var a=Gb.call(i,this.ra),e=a.hasOwnProperty(b);a[b]=d;return H(e)?new Mf(this.f,this.keys,a):(d=yd.call(i,this.keys),d.push(b),new Mf(this.f,d,a))}else return te.call(i,Af.call(i,ge.call(i,b,d),R.call(i,a)),this.f)};p.W=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,a,b,i);case 3:return Lf.call(i,b,this.ra,this.ra[b],d)}c("Invalid arity: "+arguments.length)}}();zd.call(i);
Mf.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,this,b);case 3:return K.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();function Nf(a,b,d){this.f=a;this.count=b;this.Q=d}p=Nf.prototype;p.n=function(a,b){return Jf.call(i,a,b)};p.H=function(a,b){return H(ze.call(i,b))?Jd.call(i,a,J.call(i,b,0),J.call(i,b,1)):V.call(i,Cd,a,b)};
p.D=function(){var a=this;if(H(We.call(i,a.count))){var b=Ae.call(i,a.Q);return zf.call(i,function(b){return rf.call(i,Ff,Bf.call(i,2,a.Q[b]))},b)}else return i};p.K=function(a,b){return new Nf(b,this.count,this.Q)};p.Za=!0;p.B=!0;p.J=l("f");p.I=function(a){return af.call(i,a)};p.V=l("count");
p.ua=function(a,b,d){var a=we.call(i,b),e=this.Q[a];if(H(e)){var e=yd.call(i,e),f=Gb.call(i,this.Q);f[a]=e;a=Kf.call(i,2,b,e);return H(a)?(e[O.call(i,a)]=d,new Nf(this.f,this.count,f)):(e.push(b,d),new Nf(this.f,O.call(i,this.count),f))}else return e=Gb.call(i,this.Q),e[a]=zd.call(i,b,d),new Nf(this.f,O.call(i,this.count),e)};
p.W=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,a,b,i);case 3:var e=this.Q[we.call(i,b)],f=H(e)?Kf.call(i,2,b,e):i;return H(f)?e[O.call(i,f)]:d}c("Invalid arity: "+arguments.length)}}();var Of=new Nf(i,0,function(){return{}}.call(i));Nf.prototype.call=function(){return function(a,b,d){switch(arguments.length){case 2:return K.call(i,this,b);case 3:return K.call(i,this,b,d)}c("Invalid arity: "+arguments.length)}}();
var ge=function(){function a(a){var e=i;s(a)&&(e=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,e)}function b(a){for(var a=R.call(i,a),b=Of;;)if(H(a))var f=ne.call(i,a),b=se.call(i,b,S.call(i,a),me.call(i,a)),a=f;else return b}a.b=0;a.a=function(a){a=R(a);return b.call(this,a)};return a}();ge.call(i);
function Pf(a){if(H(Ee.call(i,a)))return a;else if(H(function(){var b=Fe.call(i,a);return H(b)?b:Ge.call(i,a)}())){var b=a.lastIndexOf("/");return H(Le.call(i,b,0))?Ze.call(i,a,2):Ze.call(i,a,O.call(i,b))}else return i}function Qf(a){if(H(function(){var b=Fe.call(i,a);return H(b)?b:Ge.call(i,a)}())){var b=a.lastIndexOf("/");return H(Ne.call(i,b,-1))?Ze.call(i,a,2,b):i}else return"\ufdd0'else"}
function Rf(a,b,d,e,f,h){return mf.call(i,Ef([b]),yf.call(i,xf.call(i,Ef([d]),rf.call(i,function(b){return a.call(i,b,f)},h))),Ef([e]))}
var Tf=function Sf(b,d){return H(M.call(i,b))?N.call(i,"nil"):H(Be.call(i,b))?N.call(i,"#<undefined>"):H("\ufdd0'else")?mf.call(i,H(function(){var e=re.call(i,d,"\ufdd0'meta");return H(e)?(e=H(H(b)?b.B:b)?!0:xd.call(i,Qd,b),H(e)?ue.call(i,b):e):e}())?mf.call(i,Ef(["^"]),Sf.call(i,ue.call(i,b),d),Ef([" "])):i,H(H(H(b)?b.C:b)?!0:xd.call(i,ce,b))?ee.call(i,b,d):N.call(i,"#<",Ye.call(i,b),">")):i};Nf.prototype.C=!0;
Nf.prototype.z=function(a,b){return Rf.call(i,function(a){return Rf.call(i,Tf,""," ","",b,a)},"{",", ","}",b,a)};ce.number=!0;ee.number=function(a){return N.call(i,Ye.call(i,a))};je.prototype.C=!0;je.prototype.z=function(a,b){return Rf.call(i,Tf,"("," ",")",b,a)};X.prototype.C=!0;X.prototype.z=function(a,b){return Rf.call(i,Tf,"("," ",")",b,a)};ce["boolean"]=!0;ee["boolean"]=function(a){return N.call(i,Ye.call(i,a))};ce.string=!0;
ee.string=function(a,b){return H(Fe.call(i,a))?N.call(i,Ye.call(i,":",function(){var b=Qf.call(i,a);return H(b)?Ye.call(i,b,"/"):i}(),Pf.call(i,a))):H(Ge.call(i,a))?N.call(i,Ye.call(i,function(){var b=Qf.call(i,a);return H(b)?Ye.call(i,b,"/"):i}(),Pf.call(i,a))):H("\ufdd0'else")?N.call(i,H("\ufdd0'readably".call(i,b))?wa.call(i,a):a):i};Cf.prototype.C=!0;Cf.prototype.z=function(a,b){return Rf.call(i,Tf,"["," ","]",b,a)};bf.prototype.C=!0;
bf.prototype.z=function(a,b){return Rf.call(i,Tf,"("," ",")",b,a)};ce.array=!0;ee.array=function(a,b){return Rf.call(i,Tf,"#<Array [",", ","]>",b,a)};cf.prototype.C=!0;cf.prototype.z=function(){return N.call(i,"()")};ff.prototype.C=!0;ff.prototype.z=function(a,b){return Rf.call(i,Tf,"("," ",")",b,a)};Mf.prototype.C=!0;Mf.prototype.z=function(a,b){return Rf.call(i,function(a){return Rf.call(i,Tf,""," ","",b,a)},"{",", ","}",b,a)};function Uf(a,b,d){this.state=a;this.f=b;this.Tb=d}p=Uf.prototype;
p.C=!0;p.z=function(a,b){return mf.call(i,Ef(["#<Atom: "]),ee.call(i,this.state,b),">")};p.B=!0;p.J=l("f");p.zb=l("state");p.n=function(a,b){return fe.call(i,a,b)};
var Vf=function(){var a=i,b=function(){function a(d,h){var j=i;s(h)&&(j=Q(Array.prototype.slice.call(arguments,1),0));return b.call(this,d,j)}function b(a,d){var e=H(Ce.call(i,d))?of.call(i,ge,d):d,k=re.call(i,e,"\ufdd0'validator"),e=re.call(i,e,"\ufdd0'meta");return new Uf(a,e,k)}a.b=1;a.a=function(a){var d=S(a),a=T(a);return b.call(this,d,a)};return a}(),a=function(a,e){switch(arguments.length){case 1:return new Uf(a,i,i);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};
a.b=1;a.a=b.a;return a}();function Y(a,b){var d=a.Tb;H(d)&&!H(d.call(i,b))&&c("Validator rejected reference state");return a.state=b}
var Wf=function(){var a=i,b=function(){function a(b,d,h,j,k,n){var o=i;s(n)&&(o=Q(Array.prototype.slice.call(arguments,5),0));return Y.call(i,b,of.call(i,d,b.state,h,j,k,o))}a.b=5;a.a=function(a){var b=S(a),d=S(U(a)),j=S(U(U(a))),k=S(U(U(U(a)))),n=S(U(U(U(U(a))))),a=T(U(U(U(U(a)))));return Y.call(i,b,of.call(i,d,b.state,j,k,n,a))};return a}(),a=function(a,e,f,h,j,k){switch(arguments.length){case 2:return Y.call(i,a,e.call(i,a.state));case 3:return Y.call(i,a,e.call(i,a.state,f));case 4:return Y.call(i,
a,e.call(i,a.state,f,h));case 5:return Y.call(i,a,e.call(i,a.state,f,h,j));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.b=5;a.a=b.a;return a}();function $(a){return Pd.call(i,a)}Re=function(){var a=i;return a=function(b){switch(arguments.length){case 0:return a.call(i,1);case 1:return Math.random()*b}c("Invalid arity: "+arguments.length)}}();Se=function(a){return Math.floor(Math.random()*a)};
Vf.call(i,function(){return new Mf(i,["\ufdd0'parents","\ufdd0'descendants","\ufdd0'ancestors"],{"\ufdd0'parents":new Mf(i,[],{}),"\ufdd0'descendants":new Mf(i,[],{}),"\ufdd0'ancestors":new Mf(i,[],{})})}.call(i));var Xf=Vf.call(i,df),Yf=Vf.call(i,df),Zf=Vf.call(i,Se.call(i,100)),$f=Vf.call(i,0.5),ag=Vf.call(i,0);function bg(){Y.call(i,Xf,df);Y.call(i,Yf,df);Y.call(i,Zf,Se.call(i,100));Y.call(i,$f,0.5);return Y.call(i,ag,0)}function cg(a,b,d){for(;;)if(H(Le.call(i,qe.call(i,a),b)))a=pe.call(i,a,d);else return a}
function dg(){for(var a=kc.call(i,"ul",{id:"nums"}),b=cg.call(i,Ff.call(i,tf.call(i,3,$.call(i,Xf))),3,""),d=cg.call(i,Ff.call(i,tf.call(i,3,$.call(i,Yf))),3,""),b=rf.call(i,function(a){return kc.call(i,"li",i,oc.call(i,Ye.call(i,a)))},mf.call(i,ef.call(i,b),Ef(["?"]),d)),b=R.call(i,b);;)if(H(b))d=S.call(i,b),pc.call(i,a,d),b=U.call(i,b);else break;return rc.call(i,a,gc.call(i,"nums"))}function eg(){var a=S.call(i,$.call(i,Yf));return H(a)?(Wf.call(i,Yf,ve),Wf.call(i,Xf,pe,a),dg.call(i)):i}
function fg(){var a=S.call(i,$.call(i,Xf));return H(a)?(Wf.call(i,Xf,ve),Wf.call(i,Yf,pe,a),dg.call(i)):i}function gg(){var a=Se.call(i,$.call(i,Zf)),b=Je.call(i,$.call(i,Zf),a);return sc.call(i,gc.call(i,"expr"),Ye.call(i,a," + ",b))}
function hg(){var a=S.call(i,$.call(i,Xf)),b=S.call(i,$.call(i,Yf));return H(function(){var d=function(){var b=M.call(i,a);return H(b)?b:Me.call(i,a,$.call(i,Zf))}();return H(d)?(d=M.call(i,b),H(d)?d:Me.call(i,$.call(i,Zf),b)):d}())?(Wf.call(i,Xf,pe,$.call(i,Zf)),Y.call(i,Zf,Se.call(i,100)),dg.call(i),gg.call(i),Wf.call(i,$f,Ie,0.1),H(Ne.call(i,$.call(i,$f),1))&&Y.call(i,$f,1),Wf.call(i,ag,O)):Wf.call(i,$f,Je,0.1)}
(function(){return C.call(i,new rd(q.document),"key",function(a){a=a.keyCode;return H(L.call(i,37,a))?fg.call(i):H(L.call(i,39,a))?eg.call(i):H(L.call(i,32,a))?hg.call(i):i})}).call(i);function ig(){var a=gc.call(i,"score").getContext("2d"),b=a.createLinearGradient(0,0,766,15);b.addColorStop(0,"#F00");b.addColorStop(1,"#0F0");a.fillStyle=b;a.clearRect(0,0,766,15);return a.fillRect(0,0,Ke.call(i,766,$.call(i,$f)),15)}
function jg(){bg.call(i);dg.call(i);gg.call(i);ig.call(i);var a=Vf.call(i,-1);return Y.call(i,a,q.setInterval.call(i,function(){return H(function(){var a=Le.call(i,$.call(i,$f),0);return H(a)?a:Ne.call(i,$.call(i,ag),15)}())?(q.clearInterval.call(i,$.call(i,a)),bd(kg.call(i,$.call(i,$f)),!0)):(Wf.call(i,$f,Je,5.0E-4),ig.call(i))},20))}
function lg(){var a=new Wc;$c(a,"Welcome to make-adder");ad(a,Ye.call(i,"<p style='width: 300px'>","Move left and right with your <strong>arrow-keys</strong>. ","When the sum is in range, hit <strong>space-bar</strong> to get a new expression. ","Complete 15 additions to win the game. If time runs out you loose.","</p>","<strong>Good luck!</strong>"));fd(a);C.call(i,a,hd,function(){return jg.call(i)});return a}
function kg(a){var a=H(Me.call(i,a,0))?"Too bad. Try again!":Ye.call(i,"Nice work! You scored ",Ke.call(i,100,a),"%"),b=new Wc;$c(b,"Game Over");ad(b,a);fd(b);C.call(i,b,hd,function(){return jg.call(i)});return b}function mg(){return bd(lg.call(i),!0)}var ng="game.start".split("."),og=q;!(ng[0]in og)&&og.execScript&&og.execScript("var "+ng[0]);for(var pg;ng.length&&(pg=ng.shift());)!ng.length&&s(mg)?og[pg]=mg:og=og[pg]?og[pg]:og[pg]={};
